// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"
)

type Feed struct {
	ID            string
	Name          string
	Url           sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
	LastFetchedAt sql.NullTime
}

type Feedfollow struct {
	ID        string
	UserID    sql.NullString
	FeedID    sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Post struct {
	ID          int32
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	Title       string
	Url         string
	Description sql.NullString
	PublishedAt sql.NullTime
	FeedID      string
}

type User struct {
	ID        string
	Username  string
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	Password  string
}
