-- +goose Up
CREATE TABLE feedFollows (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    feed_id TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,

    FOREIGN KEY (feed_id) REFERENCES feeds(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);